from pathlib import Path
import re


def read(path):
    return Path(path).read_text(encoding='utf-8')

def write(path, text):
    Path(path).write_text(text, encoding='utf-8')

def replace_once(text, old, new, label):
    if old not in text:
        raise RuntimeError(f'missing marker: {label}')
    return text.replace(old, new, 1)

# 1) Route Hawaii through the Worker so authoritative Catalog prerender runs.
p='site/_routes.json'; s=read(p)
if '"/hawaii-lithium-batteries"' not in s:
    s=replace_once(s, '    "/lithium-batteries/*",\n', '    "/lithium-batteries/*",\n    "/hawaii-lithium-batteries",\n    "/hawaii-lithium-batteries/*",\n', 'hawaii worker route')
write(p,s)

# 2) Add operational certainty support to server-authoritative shipping rules.
p='site/commerce-schema-migrations.js'; s=read(p)
s=s.replace('export const COMMERCE_SCHEMA_VERSION = "2026.09.02.1";', 'export const COMMERCE_SCHEMA_VERSION = "2026.09.03.1";')
if '2026-09-03-shipping-rules-certainty-v2' not in s:
    migration='''\n  {\n    id: "2026-09-03-shipping-rules-certainty-v2",\n    description: "Shipping rule operational certainty state",\n    statements: [\n      `ALTER TABLE eus_shipping_rules ADD COLUMN certainty_state TEXT NOT NULL DEFAULT 'VERIFIED / ACTIVE'`,\n      `UPDATE eus_shipping_rules SET certainty_state='REVIEW REQUIRED' WHERE region='AK'`,\n    ],\n  },\n'''
    s=replace_once(s, '\n];\n\nlet schemaPromise', migration+'\n];\n\nlet schemaPromise', 'shipping certainty migration')
write(p,s)

p='site/shipping-rules-runtime.js'; s=read(p)
s=replace_once(s,
'const RULE_IDS = Object.freeze({LOWER48:"lower48-lithium",HI:"hawaii-lithium",AK:"alaska-lithium"});',
'const RULE_IDS = Object.freeze({LOWER48:"lower48-lithium",HI:"hawaii-lithium",HI_DELIVERY:"hawaii-address-delivery",AK:"alaska-lithium"});\nconst CERTAINTY_STATES = new Set(["VERIFIED / ACTIVE","PROVISIONAL","REVIEW REQUIRED","UNAVAILABLE"]);',
'rule ids')
s=replace_once(s,
'function view(row){if(!row)return null;return{id:row.id,region:row.region,enabled:Boolean(row.enabled),method:row.method,calculation:row.calculation,rateCents:Number(row.rate_cents||0),quoteRequired:Boolean(row.quote_required),pickupOnly:Boolean(row.pickup_only),residentialAllowed:Boolean(row.residential_allowed),minQuantity:Number(row.min_quantity||1),maxQuantity:row.max_quantity===null?null:Number(row.max_quantity),preferredConsolidationQuantity:row.preferred_consolidation_quantity===null?null:Number(row.preferred_consolidation_quantity),customerLabel:row.customer_label,timingMessage:row.timing_message,effectiveStart:row.effective_start,effectiveEnd:row.effective_end,internalNotes:row.internal_notes,version:Number(row.version||1),updatedAt:row.updated_at,updatedBy:row.updated_by};}',
'function view(row){if(!row)return null;return{id:row.id,region:row.region,enabled:Boolean(row.enabled),method:row.method,calculation:row.calculation,rateCents:Number(row.rate_cents||0),quoteRequired:Boolean(row.quote_required),pickupOnly:Boolean(row.pickup_only),residentialAllowed:Boolean(row.residential_allowed),minQuantity:Number(row.min_quantity||1),maxQuantity:row.max_quantity===null?null:Number(row.max_quantity),preferredConsolidationQuantity:row.preferred_consolidation_quantity===null?null:Number(row.preferred_consolidation_quantity),customerLabel:row.customer_label,timingMessage:row.timing_message,effectiveStart:row.effective_start,effectiveEnd:row.effective_end,internalNotes:row.internal_notes,certaintyState:CERTAINTY_STATES.has(clean(row.certainty_state,40).toUpperCase())?clean(row.certainty_state,40).toUpperCase():(Number(row.enabled)?(Number(row.quote_required)?"REVIEW REQUIRED":"VERIFIED / ACTIVE"):"UNAVAILABLE"),version:Number(row.version||1),updatedAt:row.updated_at,updatedBy:row.updated_by};}',
'view certainty')
old_seed='''  [RULE_IDS.LOWER48,"LOWER48",1,"Standard Shipping","per_battery",2799,0,0,1,1,null,null,"Lower 48 Lithium Shipping","Shipping timing varies by product and supplier fulfillment.","","","Approved 4.5 rule: $27.99 per actual lithium battery",stamp,"system"],\n  [RULE_IDS.HI,"HI",1,"Consolidated Freight","per_battery",9900,0,1,0,1,null,3,"Hawaii Freight","Warehouse / freight-terminal pickup. Shipment timing is estimated and depends on freight coordination and product eligibility.","","","Approved 4.5 rule: $99 per actual battery; preferred consolidation 3 compatible batteries",stamp,"system"],\n  [RULE_IDS.AK,"AK",1,"Review Required","per_battery",0,1,0,0,1,null,null,"Freight Review Required","Alaska lithium shipping requires a verified quote and route review.","","","No standardized Alaska lithium price is approved",stamp,"system"]\n];\n  for(const row of seeds)await db.prepare(`INSERT OR IGNORE INTO eus_shipping_rules(id,region,enabled,method,calculation,rate_cents,quote_required,pickup_only,residential_allowed,min_quantity,max_quantity,preferred_consolidation_quantity,customer_label,timing_message,effective_start,effective_end,internal_notes,updated_at,updated_by) VALUES(${Array(19).fill('?').join(',')})`).bind(...row).run();'''
new_seed='''  [RULE_IDS.LOWER48,"LOWER48",1,"Standard Shipping","per_battery",2799,0,0,1,1,null,null,"Lower 48 Lithium Shipping","Shipping timing varies by product and supplier fulfillment.","","","Approved 4.5 rule: $27.99 per actual lithium battery","VERIFIED / ACTIVE",stamp,"system"],\n  [RULE_IDS.HI,"HI",1,"Consolidated Freight","per_battery",9900,0,1,0,1,null,3,"Hawaii Freight — Honolulu Pickup","Honolulu warehouse / freight-terminal pickup. Shipment timing is estimated and not guaranteed.","","","Approved 4.5 rule: $99 per actual battery to Honolulu pickup; preferred consolidation 3 compatible batteries","VERIFIED / ACTIVE",stamp,"system"],\n  [RULE_IDS.HI_DELIVERY,"HI_DELIVERY",1,"Address Delivery Quote","flat",0,1,0,1,1,null,null,"Additional Delivery Quote Required","Delivery beyond the Honolulu pickup location is a separate quoted service.","","","No standardized Hawaii final-mile delivery price is approved","REVIEW REQUIRED",stamp,"system"],\n  [RULE_IDS.AK,"AK",1,"Review Required","per_battery",0,1,0,0,1,null,null,"Freight Review Required","Alaska lithium shipping requires a verified quote and route review.","","","No standardized Alaska lithium price is approved","REVIEW REQUIRED",stamp,"system"]\n];\n  for(const row of seeds)await db.prepare(`INSERT OR IGNORE INTO eus_shipping_rules(id,region,enabled,method,calculation,rate_cents,quote_required,pickup_only,residential_allowed,min_quantity,max_quantity,preferred_consolidation_quantity,customer_label,timing_message,effective_start,effective_end,internal_notes,certainty_state,updated_at,updated_by) VALUES(${Array(20).fill('?').join(',')})`).bind(...row).run();'''
s=replace_once(s, old_seed, new_seed, 'shipping seed block')
s=s.replace("ORDER BY CASE region WHEN 'LOWER48' THEN 1 WHEN 'HI' THEN 2 WHEN 'AK' THEN 3 ELSE 9 END", "ORDER BY CASE region WHEN 'LOWER48' THEN 1 WHEN 'HI' THEN 2 WHEN 'HI_DELIVERY' THEN 3 WHEN 'AK' THEN 4 ELSE 9 END")
old_update='''const updated={enabled:raw.enabled===undefined?Boolean(existing.enabled):bool(raw.enabled),method:clean(raw.method??existing.method,120),calculation,rateCents:rate,quoteRequired:raw.quoteRequired===undefined?Boolean(existing.quote_required):bool(raw.quoteRequired),pickupOnly:raw.pickupOnly===undefined?Boolean(existing.pickup_only):bool(raw.pickupOnly),residentialAllowed:raw.residentialAllowed===undefined?Boolean(existing.residential_allowed):bool(raw.residentialAllowed),minQuantity:Math.max(1,int(raw.minQuantity,existing.min_quantity||1)),maxQuantity:raw.maxQuantity===""||raw.maxQuantity===null?null:int(raw.maxQuantity,existing.max_quantity),preferredConsolidationQuantity:raw.preferredConsolidationQuantity===""||raw.preferredConsolidationQuantity===null?null:int(raw.preferredConsolidationQuantity,existing.preferred_consolidation_quantity),customerLabel:clean(raw.customerLabel??existing.customer_label,180),timingMessage:clean(raw.timingMessage??existing.timing_message,500),effectiveStart:clean(raw.effectiveStart??existing.effective_start,40),effectiveEnd:clean(raw.effectiveEnd??existing.effective_end,40),internalNotes:clean(raw.internalNotes??existing.internal_notes,2000)};const stamp=now();await db.prepare(`UPDATE eus_shipping_rules SET enabled=?,method=?,calculation=?,rate_cents=?,quote_required=?,pickup_only=?,residential_allowed=?,min_quantity=?,max_quantity=?,preferred_consolidation_quantity=?,customer_label=?,timing_message=?,effective_start=?,effective_end=?,internal_notes=?,version=version+1,updated_at=?,updated_by=? WHERE id=?`).bind(updated.enabled?1:0,updated.method,updated.calculation,updated.rateCents,updated.quoteRequired?1:0,updated.pickupOnly?1:0,updated.residentialAllowed?1:0,updated.minQuantity,updated.maxQuantity,updated.preferredConsolidationQuantity,updated.customerLabel,updated.timingMessage,updated.effectiveStart,updated.effectiveEnd,updated.internalNotes,stamp,auth.email,ruleId).run();'''
new_update='''const certaintyCandidate=clean(raw.certaintyState??existing.certainty_state,40).toUpperCase();const updated={enabled:raw.enabled===undefined?Boolean(existing.enabled):bool(raw.enabled),method:clean(raw.method??existing.method,120),calculation,rateCents:rate,quoteRequired:raw.quoteRequired===undefined?Boolean(existing.quote_required):bool(raw.quoteRequired),pickupOnly:raw.pickupOnly===undefined?Boolean(existing.pickup_only):bool(raw.pickupOnly),residentialAllowed:raw.residentialAllowed===undefined?Boolean(existing.residential_allowed):bool(raw.residentialAllowed),minQuantity:Math.max(1,int(raw.minQuantity,existing.min_quantity||1)),maxQuantity:raw.maxQuantity===""||raw.maxQuantity===null?null:int(raw.maxQuantity,existing.max_quantity),preferredConsolidationQuantity:raw.preferredConsolidationQuantity===""||raw.preferredConsolidationQuantity===null?null:int(raw.preferredConsolidationQuantity,existing.preferred_consolidation_quantity),customerLabel:clean(raw.customerLabel??existing.customer_label,180),timingMessage:clean(raw.timingMessage??existing.timing_message,500),effectiveStart:clean(raw.effectiveStart??existing.effective_start,40),effectiveEnd:clean(raw.effectiveEnd??existing.effective_end,40),internalNotes:clean(raw.internalNotes??existing.internal_notes,2000),certaintyState:CERTAINTY_STATES.has(certaintyCandidate)?certaintyCandidate:(Number(existing.enabled)?"VERIFIED / ACTIVE":"UNAVAILABLE")};const stamp=now();await db.prepare(`UPDATE eus_shipping_rules SET enabled=?,method=?,calculation=?,rate_cents=?,quote_required=?,pickup_only=?,residential_allowed=?,min_quantity=?,max_quantity=?,preferred_consolidation_quantity=?,customer_label=?,timing_message=?,effective_start=?,effective_end=?,internal_notes=?,certainty_state=?,version=version+1,updated_at=?,updated_by=? WHERE id=?`).bind(updated.enabled?1:0,updated.method,updated.calculation,updated.rateCents,updated.quoteRequired?1:0,updated.pickupOnly?1:0,updated.residentialAllowed?1:0,updated.minQuantity,updated.maxQuantity,updated.preferredConsolidationQuantity,updated.customerLabel,updated.timingMessage,updated.effectiveStart,updated.effectiveEnd,updated.internalNotes,updated.certaintyState,stamp,auth.email,ruleId).run();'''
s=replace_once(s, old_update, new_update, 'shipping admin update')
write(p,s)

# 3) Admin can manage certainty state without exposing internal labels to customers.
p='site/admin-shipping-rules.js'; s=read(p)
old='<div class="shipping-rule-grid"><label>Method<input name="method" value="${esc(rule.method)}"></label>'
new='<div class="shipping-rule-grid"><label>Operational status<select name="certaintyState"><option ${rule.certaintyState===\'VERIFIED / ACTIVE\'?\'selected\':\'\'}>VERIFIED / ACTIVE</option><option ${rule.certaintyState===\'PROVISIONAL\'?\'selected\':\'\'}>PROVISIONAL</option><option ${rule.certaintyState===\'REVIEW REQUIRED\'?\'selected\':\'\'}>REVIEW REQUIRED</option><option ${rule.certaintyState===\'UNAVAILABLE\'?\'selected\':\'\'}>UNAVAILABLE</option></select></label><label>Method<input name="method" value="${esc(rule.method)}"></label>'
s=replace_once(s, old, new, 'admin certainty select')
s=replace_once(s, "const payload={enabled:f.elements.enabled.checked,method:fd.get('method')", "const payload={enabled:f.elements.enabled.checked,certaintyState:fd.get('certaintyState'),method:fd.get('method')", 'admin certainty payload')
write(p,s)

# 4) Public Hawaii page: simple customer experience, Honolulu pickup clarity, smaller review form.
p='site/hawaii-lithium-batteries.html'; s=read(p)
s=s.replace('request Hawaii consolidated freight at $99 per actual battery with warehouse pickup.', 'buy eligible batteries with $99-per-battery freight to the Honolulu warehouse / freight-terminal pickup location.')
s=s.replace('Eligible orders use coordinated freight with warehouse or freight-terminal pickup.', 'Eligible orders use $99-per-battery freight to the Honolulu warehouse / freight-terminal pickup location. Elevation handles the freight coordination and sends the customer the pickup details when confirmed.')
s=s.replace('<h3>$99 per actual battery under the current approved rule</h3><p><strong>Warehouse / freight-terminal pickup.</strong> Shipment timing is estimated and depends on freight coordination and product eligibility.</p>', '<h3>$99 per actual battery to the Honolulu pickup location</h3><p><strong>Honolulu warehouse / freight-terminal pickup.</strong> Timing is estimated and not guaranteed. Delivery from the pickup location to a home, business, jobsite or other address is an additional quoted service.</p>')
new_how='''<section class="section" id="how-it-works"><div class="container"><div class="section-heading"><p class="eyebrow">SIMPLE HAWAII PURCHASE</p><h2>Buy the battery. Elevation handles the freight process.</h2><p>Customers do not choose carriers, batches, compliance packages or freight routes. Elevation keeps that work on the operations side and provides meaningful updates as the order moves toward Honolulu pickup.</p></div><div class="hawaii-steps"><article class="hawaii-step"><strong>1 · Choose a Battery</strong><p>Shipping Available batteries can be purchased with the current $99-per-actual-battery Honolulu pickup freight rule.</p></article><article class="hawaii-step"><strong>2 · Complete Simple Checkout</strong><p>Review the merchandise, quantity, Hawaii freight and total. Elevation coordinates the shipping work after purchase.</p></article><article class="hawaii-step"><strong>3 · Receive Updates</strong><p>Elevation sends order and freight milestones, then confirmed Honolulu pickup details when the shipment is ready.</p></article></div><div class="hawaii-status-grid" style="margin-top:14px"><article class="hawaii-status-card is-approved"><strong>Shipping Available</strong><p>Buy Now is available for the exact battery under the current Hawaii route.</p></article><article class="hawaii-status-card"><strong>Freight Review Required</strong><p>Request a short shipping review. Elevation verifies the battery and contacts you with the next step.</p></article><article class="hawaii-status-card"><strong>Currently Unavailable</strong><p>No payment is collected for a Hawaii route that cannot currently be supported.</p></article></div><p style="margin-top:16px"><strong>Need delivery beyond the Honolulu pickup location?</strong> Additional delivery charges apply. Call or text <a href="tel:+12088134998">208-813-4998</a> or email <a href="mailto:casey@elevationupscales.com">casey@elevationupscales.com</a> for a delivery quote.</p></div></section>'''
s,n=re.subn(r'<section class="section" id="how-it-works">[\s\S]*?</section>', new_how, s, count=1)
if n!=1: raise RuntimeError('how-it-works section replacement failed')
new_request='''<section class="hawaii-request-section" id="hawaii-request"><div class="container hawaii-request-wrap"><div><p class="eyebrow">FREIGHT REVIEW REQUIRED</p><h2>Request a short Hawaii shipping review.</h2><p>If the exact battery is not yet marked Shipping Available, send the minimum information below. Elevation will verify the battery and Hawaii freight path and contact you with the next step. No payment is collected by this request.</p></div><form class="hawaii-request-form" data-hawaii-request-form><div class="hawaii-request-grid"><label>Name<input name="name" maxlength="120" required autocomplete="name"></label><label>Email<input name="email" type="email" maxlength="180" required autocomplete="email"></label><label>Phone <small>(optional)</small><input name="phone" maxlength="40" autocomplete="tel"></label><label>Island / destination<select name="island" required><option>Oahu</option><option>Maui</option><option>Kauai</option><option>Hawaii Island / Big Island</option><option>Hawaii — General</option><option>Other / Confirm</option></select></label><label>Quantity<input name="quantity" type="number" min="1" max="100" value="1" required></label><label class="wide">Battery or product<input name="productInterest" maxlength="240" required placeholder="Battery name or SKU"></label><label class="wide hawaii-consent"><input name="consent" type="checkbox" required><span>I agree to be contacted by Elevation UpScales about this Hawaii shipping review.</span></label></div><p class="hawaii-request-disclosure"><strong>Review requests do not collect payment.</strong> Shipping Available batteries use $99 per actual battery to the Honolulu pickup location. Address delivery beyond that point is a separate quote.</p><button class="button button-primary" type="submit">Reserve / Request Shipping Review</button><p class="hawaii-request-status" data-hawaii-request-status role="status"></p></form></div></section>'''
s,n=re.subn(r'<section class="hawaii-request-section" id="hawaii-request">[\s\S]*?</section>\s*<section class="lithium-market"', new_request+'\n<section class="lithium-market"', s, count=1)
if n!=1: raise RuntimeError('review request section replacement failed')
s=s.replace('Each card shows a simple current shipping state; detailed freight education remains above.', 'Each card shows a simple current shipping state. $99-per-battery freight is to the Honolulu pickup location; address delivery is an additional quoted service.')
write(p,s)

# 5) Checkout presentation: keep simple contact fields, hide only address fields for Honolulu pickup.
p='site/checkout/index.html'; s=read(p)
s=s.replace('/store-checkout.js?v=4.5.0', '/store-checkout.js?v=4.5.1')
s=s.replace('<div id="checkout-contact-shipping-label" class="eus-checkout-section-label">Contact &amp; shipping</div>', '<div id="checkout-contact-shipping-label" class="eus-checkout-section-label">Contact &amp; shipping</div>')
s=s.replace('<label class="eus-checkout-field-wide">\n              <span>Address</span>', '<label class="eus-checkout-field-wide eus-checkout-address-field">\n              <span>Address</span>')
s=s.replace('<label class="eus-checkout-field-wide">\n              <span>Address 2</span>', '<label class="eus-checkout-field-wide eus-checkout-address-field">\n              <span>Address 2</span>')
s=s.replace('<label>\n              <span>City</span>', '<label class="eus-checkout-address-field">\n              <span>City</span>')
s=s.replace('<div class="eus-checkout-row">\n              <label>\n                <span>State</span>', '<div class="eus-checkout-row eus-checkout-address-field">\n              <label>\n                <span>State</span>')
old_panel='<section id="checkout-hawaii-freight" class="eus-checkout-hawaii" hidden><p class="eus-checkout-step">HAWAII LITHIUM SHIPPING &amp; FREIGHT</p><h3 id="checkout-hawaii-state">Freight Review Required</h3><p id="checkout-hawaii-math"></p><p><strong>Warehouse / freight-terminal pickup.</strong> Shipment timing is estimated and depends on freight coordination and product eligibility.</p><a id="checkout-hawaii-reserve" class="eus-checkout-hawaii-cta" href="/hawaii-lithium-batteries#hawaii-request">Reserve / Request Shipping Review</a></section>'
new_panel='<section id="checkout-hawaii-freight" class="eus-checkout-hawaii" hidden><p class="eus-checkout-step">HAWAII LITHIUM SHIPPING &amp; FREIGHT</p><h3 id="checkout-hawaii-state">Freight Review Required</h3><p id="checkout-hawaii-math"></p><p><strong>$99 per actual battery covers freight to the Honolulu warehouse / freight-terminal pickup location.</strong> Timing is estimated and not guaranteed.</p><p>Need delivery from the Honolulu pickup location to your home, business or another address? <strong>Additional delivery charges apply.</strong> Contact Elevation for a delivery quote: <a href="tel:+12088134998">208-813-4998</a> · <a href="mailto:casey@elevationupscales.com">casey@elevationupscales.com</a>.</p><a id="checkout-hawaii-reserve" class="eus-checkout-hawaii-cta" href="/hawaii-lithium-batteries#hawaii-request">Reserve / Request Shipping Review</a></section>'
s=replace_once(s, old_panel, new_panel, 'checkout Hawaii panel')
old_success='<section id="checkout-success" class="eus-checkout-success" hidden>\n          <h2>Payment complete</h2>\n          <p id="checkout-success-reference"></p>\n          <a href="/store">Return to Store</a>\n        </section>'
new_success='<section id="checkout-success" class="eus-checkout-success" hidden>\n          <h2>Payment complete</h2>\n          <p id="checkout-success-reference"></p>\n          <section id="checkout-hawaii-next" hidden><p class="eus-checkout-step">WHAT HAPPENS NEXT</p><ol><li><strong>Order Received.</strong> Elevation verifies the exact product, current inventory and freight readiness. Normally you do not need to take action.</li><li><strong>Elevation Coordinates Freight.</strong> Elevation handles the applicable supplier, documentation, consolidation and freight coordination.</li><li><strong>You Receive Updates.</strong> Updates may include Order Confirmed, Freight In Process, Shipment Scheduled, In Transit, Arrived in Honolulu and Ready for Pickup. Dates are only provided when confirmed.</li><li><strong>Pickup Information.</strong> Once ready, Elevation sends the confirmed Honolulu pickup location, address, instructions, order reference and any verified pickup requirements.</li><li><strong>Optional Address Delivery.</strong> For delivery beyond the Honolulu pickup location, contact Elevation for an additional delivery quote at 208-813-4998 or casey@elevationupscales.com.</li></ol></section>\n          <a href="/store">Return to Store</a>\n        </section>'
s=replace_once(s, old_success, new_success, 'checkout Hawaii next steps')
write(p,s)

# 6) Checkout client: payment only for Shipping Available Hawaii SKUs; address form hidden only for pickup.
p='site/store-checkout.js'; s=read(p)
s=replace_once(s, '  const shippingFields = document.querySelector("#checkout-shipping-fields");', '  const shippingFields = document.querySelector("#checkout-shipping-fields");\n  const addressFields = [...document.querySelectorAll(".eus-checkout-address-field")];\n  const hawaiiNext = document.querySelector("#checkout-hawaii-next");', 'checkout refs')
old_ready='''  const formReady = () => {\n    const address = shipping();\n    const buyer = customer();\n    return Boolean(\n      address.fullName &&\n      address.address1 &&\n      address.city &&\n      /^[A-Z]{2}$/.test(address.state) &&\n      /^\\d{5}(?:-\\d{4})?$/.test(address.postalCode) &&\n      /^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$/.test(buyer.email)\n    );\n  };'''
new_ready='''  const formReady = () => {\n    const address = shipping();\n    const buyer = customer();\n    const emailReady = /^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$/.test(buyer.email);\n    if (quote?.hawaii?.customerState === "shipping_available") return Boolean(address.fullName && emailReady);\n    return Boolean(address.fullName && address.address1 && address.city && /^[A-Z]{2}$/.test(address.state) && /^\\d{5}(?:-\\d{4})?$/.test(address.postalCode) && emailReady);\n  };'''
s=replace_once(s, old_ready, new_ready, 'checkout form ready')
s=s.replace('if (shippingLabelEl) shippingLabelEl.textContent = isHawaii ? "Hawaii Consolidated Freight" : "Shipping";', 'if (shippingLabelEl) shippingLabelEl.textContent = isHawaii ? "Hawaii Freight — Honolulu Pickup" : "Shipping";')
s=s.replace('if (contactShippingLabel) contactShippingLabel.hidden = isHawaii;\n    if (shippingFields) shippingFields.hidden = isHawaii;', 'if (contactShippingLabel) { contactShippingLabel.hidden = false; contactShippingLabel.textContent = isHawaii ? "Contact & pickup" : "Contact & shipping"; }\n    if (shippingFields) shippingFields.hidden = false;\n    addressFields.forEach((field) => { field.hidden = isHawaii; });')
s=s.replace('if (customerState === "shipping_available") hawaiiMath.textContent = `Battery ${money(next.unitPriceCents)} × ${next.quantity}. Hawaii Freight ${money(freightRate)} × ${batteryCount} actual batter${batteryCount === 1 ? "y" : "ies"} = ${money(next.shippingCents)}. Order total ${money(next.totalCents)} before any applicable tax.`;', 'if (customerState === "shipping_available") hawaiiMath.textContent = `Battery ${money(next.unitPriceCents)} × ${next.quantity}. Honolulu pickup freight ${money(freightRate)} × ${batteryCount} actual batter${batteryCount === 1 ? "y" : "ies"} = ${money(next.shippingCents)}. Order total ${money(next.totalCents)} before any applicable tax.`;')
s=s.replace('if (hawaiiReserve) hawaiiReserve.href = next.hawaii?.requestUrl || "/hawaii-lithium-batteries#hawaii-request";\n      paypalEl.hidden = true;', 'if (hawaiiReserve) { hawaiiReserve.href = next.hawaii?.requestUrl || "/hawaii-lithium-batteries#hawaii-request"; hawaiiReserve.hidden = customerState === "shipping_available"; hawaiiReserve.textContent = customerState === "unavailable" ? "Check Availability / Contact Elevation" : "Reserve / Request Shipping Review"; }\n      paypalEl.hidden = customerState !== "shipping_available";')
s=s.replace('if (body.hawaii) { const stateValue=String(body.hawaii.customerState||"review_required"); setStatus(stateValue==="shipping_available" ? "Hawaii shipping rule loaded. Reserve the order for freight coordination before payment." : stateValue==="unavailable" ? "This battery is currently unavailable for the Hawaii freight path. No payment will be collected." : "Freight Review Required. Reserve / request shipping review before payment.", stateValue==="unavailable" ? "error" : "ready"); }', 'if (body.hawaii) { const stateValue=String(body.hawaii.customerState||"review_required"); setStatus(stateValue==="shipping_available" ? "Hawaii shipping is available. Complete your contact information and use Buy Now — Elevation handles the freight coordination." : stateValue==="unavailable" ? "This battery is currently unavailable for Hawaii shipping. No payment will be collected." : "Freight Review Required. Send a short review request and Elevation will contact you with the next step.", stateValue==="unavailable" ? "error" : "ready"); }')
s=s.replace('setStatus("Complete the shipping and contact information before paying.", "error");', 'setStatus(quote?.hawaii ? "Enter your name and email before paying. Elevation will send confirmed Honolulu pickup details later." : "Complete the shipping and contact information before paying.", "error");')
s=s.replace('successEl.hidden = false;', 'if (hawaiiNext) hawaiiNext.hidden = !(quote?.hawaii?.customerState === "shipping_available");\n        successEl.hidden = false;', 1)
s=s.replace('      if (quote.hawaii) return;\n      if (await loadPayPal()) {', '      if (quote.hawaii && quote.hawaii.customerState !== "shipping_available") return;\n      if (await loadPayPal()) {')
write(p,s)

# 7) Server: paid Hawaii checkout for Shipping Available only; no fabricated pickup address.
p='site/store-checkout-server.js'; s=read(p)
s=s.replace('warehousePickupOnly:Boolean(rule?.pickupOnly??true),requiresReservation:true,paymentAllowed:false,timing:rule?.timingMessage||"Warehouse / freight-terminal pickup. Shipment timing is estimated and depends on freight coordination and product eligibility.",requestUrl', 'warehousePickupOnly:Boolean(rule?.pickupOnly??true),pickupLocationLabel:"Honolulu warehouse / freight-terminal pickup location",requiresReservation:(hawaiiStatus?.customerState||"review_required")!=="shipping_available",paymentAllowed:(hawaiiStatus?.customerState||"review_required")==="shipping_available",finalMileQuoteRequired:true,finalMileMessage:"Delivery beyond the Honolulu pickup location is an additional quoted service.",supportPhone:"208-813-4998",supportEmail:"casey@elevationupscales.com",timing:rule?.timingMessage||"Honolulu warehouse / freight-terminal pickup. Shipment timing is estimated and not guaranteed.",requestUrl')
s=replace_once(s, '  if (quote.hawaii?.requiresReservation) return json({error:"Hawaii lithium orders use consolidated freight reservation before payment and carrier tender.",hawaiiFreight:true,requestUrl:quote.hawaii.requestUrl,quote},409);', '  if (quote.hawaii?.customerState === "review_required") return json({error:"Freight Review Required. Elevation will verify the battery and Hawaii freight path and contact you with the next step.",hawaiiFreight:true,requestUrl:quote.hawaii.requestUrl,quote},409);\n  if (quote.hawaii?.customerState === "unavailable") return json({error:"Currently Unavailable for Hawaii Shipping",hawaiiFreight:true,requestUrl:quote.hawaii.requestUrl,quote},409);', 'Hawaii order boundary')
s=replace_once(s, '  const address = normalizeAddress(raw?.shipping);\n  if (quote.physical && !validAddress(address)) return json({ error: "A valid U.S. shipping address is required" }, 400);', '  const address = normalizeAddress(raw?.shipping);\n  const hawaiiPickup = quote.hawaii?.customerState === "shipping_available" && quote.hawaii?.warehousePickupOnly;\n  if (quote.physical && !hawaiiPickup && !validAddress(address)) return json({ error: "A valid U.S. shipping address is required" }, 400);\n  if (hawaiiPickup && (!address.fullName || !validEmail(customer.email))) return json({ error: "Name and email are required for Hawaii pickup orders" }, 400);', 'Hawaii address validation')
s=s.replace('  if (quote.physical) purchaseUnit.shipping={name:{full_name:address.fullName},address:{address_line_1:address.address1,...(address.address2?{address_line_2:address.address2}:{}),admin_area_2:address.city,admin_area_1:address.state,postal_code:address.postalCode,country_code:address.countryCode}};', '  if (quote.physical && !(quote.hawaii?.customerState === "shipping_available" && quote.hawaii?.warehousePickupOnly)) purchaseUnit.shipping={name:{full_name:address.fullName},address:{address_line_1:address.address1,...(address.address2?{address_line_2:address.address2}:{}),admin_area_2:address.city,admin_area_1:address.state,postal_code:address.postalCode,country_code:address.countryCode}};')
s=s.replace('          shipping_preference: quote.physical ? "SET_PROVIDED_ADDRESS" : "NO_SHIPPING",', '          shipping_preference: quote.physical && !(quote.hawaii?.customerState === "shipping_available" && quote.hawaii?.warehousePickupOnly) ? "SET_PROVIDED_ADDRESS" : "NO_SHIPPING",')
s=s.replace('JSON.stringify({...quote.doba,shippingRule:quote.shippingRule||{},promotion:', 'JSON.stringify({...quote.doba,shippingRule:quote.shippingRule||{},hawaii:quote.hawaii||null,promotion:')
write(p,s)

# 8) Server-rendered Hawaii cards reflect Honolulu pickup and optional delivery quote.
p='site/_worker.js'; s=read(p)
s=s.replace('<p><strong>Hawaii Freight</strong><span>$99 per actual battery when shipping is approved</span></p><p><strong>Fulfillment</strong><span>Warehouse / freight-terminal pickup</span></p>', '<p><strong>Hawaii Freight</strong><span>$99 per actual battery when shipping is approved</span></p><p><strong>Pickup</strong><span>Honolulu warehouse / freight-terminal location</span></p><p><strong>Address Delivery</strong><span>Additional charge · quote required</span></p>')
write(p,s)

print('Final 4.5 Hawaii UX + prerender repair applied')
