from pathlib import Path


def replace_once(text, old, new, label):
    if old not in text:
        raise SystemExit(f"{label} anchor missing")
    return text.replace(old, new, 1)

p = Path("site/commerce-pricing-runtime.js")
s = p.read_text()
anchor = 'function marginPercent(revenue,cost){if(!(revenue>0)||!(cost>=0))return null;return Math.round(((revenue-cost)/revenue)*1000)/10;}\n'
helper = 'function classifyReviewNote(value){const note=clean(value,500).toLowerCase();if(!note)return{kind:"none",blocking:false,review:false};if(/hold|blocked|do not publish|unavailable|zero stock|out of stock/.test(note))return{kind:"blocking",blocking:true,review:false};if(/review|verify|verification|confirm|pending|manual/.test(note))return{kind:"verification",blocking:false,review:true};if(/import|doba|supplier|catalog|source|pricing|price|shipping|route/.test(note))return{kind:"operational",blocking:false,review:false};return{kind:"informational",blocking:false,review:false};}\n'
if helper not in s:
    s = replace_once(s, anchor, anchor + helper, "review helper")

old = 'const products=[];const supplierCounts={};let missingCost=0,dobaSourceMatched=0,sourceCostMismatch=0,promoFloorFailures=0,storedBelowProtectedFloor=0,published=0,reviewCount=0,actualLithium=0;'
new = 'const products=[];const supplierCounts={};let missingCost=0,dobaSourceMatched=0,sourceCostMismatch=0,promoFloorFailures=0,storedBelowProtectedFloor=0,published=0,actualLithium=0,blockedProducts=0,reviewProducts=0,informationalProducts=0,cleanProducts=0,publishHold=0,draftProducts=0,shippingHold=0,shippingUnverified=0,missingSourceSnapshot=0,annotatedProducts=0;'
s = replace_once(s, old, new, "counter")

old = '''    const flags=[];if(!authoritativeCostCents)flags.push("COST MISSING");if(sourceCost&&product.catalogCostCents>0&&Math.abs(sourceCost-product.catalogCostCents)>2)flags.push("COST SOURCE MISMATCH");if(source&&/STALE|MISSING/i.test(source.state))flags.push("SUPPLIER SOURCE STALE");if(storedBelow)flags.push("STORED PRICE BELOW LITHIUM FLOOR");if(promoBelow)flags.push("PROMO BELOW PROTECTED FLOOR");if(product.publishStatus==="hold"||product.reviewState)flags.push("CATALOG REVIEW/HOLD");if(product.shippingStatus&&product.shippingStatus!=="verified"&&product.storeSection!=="lithium-batteries")flags.push("SHIPPING REVIEW");if(flags.length)reviewCount+=1;\n    const supplierLabel=product.supplier||product.sourceType||"other";supplierCounts[supplierLabel]=(supplierCounts[supplierLabel]||0)+1;\n    products.push({...product,actualLithiumBattery:actualBattery,batteryUnitsPerCatalogUnit:batteryUnitsPerCatalogUnit({...product,title:product.title}),authoritativeCostCents,costEvidence,sourceSnapshot:source,effectiveListPriceCents:Number(pricing.priceCents||product.catalogPriceCents),promotion:{active:Boolean(pricing?.promotion?.active),couponEligible:Boolean(pricing?.promotion?.couponEligible),couponCode:clean(pricing?.promotion?.couponCode,40),couponPercent:int(pricing?.promotion?.couponPercent,0),couponPriceCents,pricingMode:clean(pricing?.promotion?.pricingMode,80),protectedNormalFloorCents,protectedPromoFloorCents,shippingDiscounted:Boolean(pricing?.promotion?.shippingDiscounted)},merchandiseMargin:{listGrossCents:Math.max(0,Number(pricing.priceCents||0)-authoritativeCostCents),listGrossPercent:marginPercent(Number(pricing.priceCents||0),authoritativeCostCents),promoGrossCents:Math.max(0,couponPriceCents-authoritativeCostCents),promoGrossPercent:marginPercent(couponPriceCents,authoritativeCostCents)},flags});\n'''
new = '''    const blockers=[],reviews=[],advisories=[];const reviewNote=classifyReviewNote(product.reviewState);if(product.reviewState)annotatedProducts+=1;\n    if(!authoritativeCostCents)blockers.push("COST MISSING");if(sourceCost&&product.catalogCostCents>0&&Math.abs(sourceCost-product.catalogCostCents)>2)blockers.push("COST SOURCE MISMATCH");if(source&&/STALE|MISSING/i.test(source.state))reviews.push("SUPPLIER SOURCE STALE");if(dobaLike&&!source){reviews.push("SUPPLIER SOURCE SNAPSHOT MISSING");missingSourceSnapshot+=1;}if(storedBelow)advisories.push("CATALOG PRICE DRIFT — LIVE PRICING PROTECTED");if(promoBelow)blockers.push("PROMO BELOW PROTECTED FLOOR");if(product.publishStatus==="hold"){blockers.push("PUBLISH HOLD");publishHold+=1;}else if(product.publishStatus==="draft"){reviews.push("DRAFT — NOT PUBLISHED");draftProducts+=1;}if(reviewNote.blocking)blockers.push("REVIEW NOTE CONTAINS BLOCKING LANGUAGE");else if(reviewNote.review)reviews.push("REVIEW NOTE NEEDS VERIFICATION");else if(reviewNote.kind==="operational"||reviewNote.kind==="informational")advisories.push("CATALOG NOTE — INFORMATIONAL");if(product.shippingStatus==="hold"&&product.storeSection!=="lithium-batteries"){blockers.push("SHIPPING HOLD");shippingHold+=1;}else if(product.shippingStatus&&product.shippingStatus!=="verified"&&product.storeSection!=="lithium-batteries"){reviews.push("SHIPPING UNVERIFIED");shippingUnverified+=1;}\n    const severity=blockers.length?"BLOCKED":reviews.length?"REVIEW":advisories.length?"INFO":"CLEAN";if(severity==="BLOCKED")blockedProducts+=1;else if(severity==="REVIEW")reviewProducts+=1;else if(severity==="INFO")informationalProducts+=1;else cleanProducts+=1;\n    const supplierLabel=product.supplier||product.sourceType||"other";supplierCounts[supplierLabel]=(supplierCounts[supplierLabel]||0)+1;\n    products.push({...product,actualLithiumBattery:actualBattery,batteryUnitsPerCatalogUnit:batteryUnitsPerCatalogUnit({...product,title:product.title}),authoritativeCostCents,costEvidence,sourceSnapshot:source,effectiveListPriceCents:Number(pricing.priceCents||product.catalogPriceCents),promotion:{active:Boolean(pricing?.promotion?.active),couponEligible:Boolean(pricing?.promotion?.couponEligible),couponCode:clean(pricing?.promotion?.couponCode,40),couponPercent:int(pricing?.promotion?.couponPercent,0),couponPriceCents,pricingMode:clean(pricing?.promotion?.pricingMode,80),protectedNormalFloorCents,protectedPromoFloorCents,shippingDiscounted:Boolean(pricing?.promotion?.shippingDiscounted)},merchandiseMargin:{listGrossCents:Math.max(0,Number(pricing.priceCents||0)-authoritativeCostCents),listGrossPercent:marginPercent(Number(pricing.priceCents||0),authoritativeCostCents),promoGrossCents:Math.max(0,couponPriceCents-authoritativeCostCents),promoGrossPercent:marginPercent(couponPriceCents,authoritativeCostCents)},reviewNoteClass:reviewNote.kind,severity,blockers,reviews,advisories,flags:[...blockers,...reviews,...advisories]});\n'''
s = replace_once(s, old, new, "flags")
old = 'summary:{catalogProducts:products.length,published,actualLithium,dobaSourceRecords:dobaSource.count,dobaSourceMatched,missingAuthoritativeCost:missingCost,sourceCostMismatch,storedBelowProtectedFloor,promoFloorFailures,needsReview:reviewCount,supplierCounts}'
new = 'summary:{catalogProducts:products.length,published,actualLithium,dobaSourceRecords:dobaSource.count,dobaSourceMatched,missingAuthoritativeCost:missingCost,sourceCostMismatch,storedBelowProtectedFloor,promoFloorFailures,blockedProducts,reviewProducts,informationalProducts,cleanProducts,actionRequired:blockedProducts+reviewProducts,publishHold,draftProducts,shippingHold,shippingUnverified,missingSourceSnapshot,annotatedProducts,supplierCounts}'
s = replace_once(s, old, new, "summary")
p.write_text(s)

p = Path("site/admin-commerce-pricing.html")
h = p.read_text()
old = '<article><span>Catalog Products</span><strong id="pricing-count-total">—</strong></article><article><span>Published</span><strong id="pricing-count-published">—</strong></article><article><span>Actual Lithium</span><strong id="pricing-count-lithium">—</strong></article><article><span>Missing Cost</span><strong id="pricing-count-missing">—</strong></article><article><span>Cost Mismatch</span><strong id="pricing-count-mismatch">—</strong></article><article><span>Needs Review</span><strong id="pricing-count-review">—</strong></article>'
new = '<article><span>Catalog Products</span><strong id="pricing-count-total">—</strong></article><article><span>Published</span><strong id="pricing-count-published">—</strong></article><article><span>Actual Lithium</span><strong id="pricing-count-lithium">—</strong></article><article><span>Blocked</span><strong id="pricing-count-blocked">—</strong></article><article><span>Review</span><strong id="pricing-count-review">—</strong></article><article><span>Price Drift</span><strong id="pricing-count-drift">—</strong></article><article><span>Missing Cost</span><strong id="pricing-count-missing">—</strong></article><article><span>Cost Mismatch</span><strong id="pricing-count-mismatch">—</strong></article>'
h = replace_once(h, old, new, "summary cards")
old = '<label>Review<select id="pricing-risk"><option value="all">All</option><option value="review">Needs review</option><option value="clean">No flags</option></select></label>'
new = '<label>Status<select id="pricing-risk"><option value="all">All</option><option value="blocked">Blocked</option><option value="review">Review</option><option value="info">Info / Drift</option><option value="clean">Clean</option><option value="drift">Price Drift</option></select></label>'
h = replace_once(h, old, new, "risk filter")
old = '<section class="pricing-notice"><strong>READ-ONLY CONTROL PASS</strong><span>Supplier data is evidence until reviewed. Current production shipping and promotion rules remain authoritative.</span></section>'
new = '<section class="pricing-notice"><strong>READ-ONLY CONTROL PASS</strong><span>Supplier data is evidence until reviewed. Stored Lithium price drift is shown separately from live checkout safety; current promotion and Shipping Rules remain authoritative.</span></section>'
h = replace_once(h, old, new, "notice")
p.write_text(h)

p = Path("site/admin-commerce-pricing.js")
j = p.read_text()
old = '$("pricing-count-lithium").textContent=Number(s.actualLithium||0).toLocaleString();$("pricing-count-missing").textContent=Number(s.missingAuthoritativeCost||0).toLocaleString();$("pricing-count-mismatch").textContent=Number(s.sourceCostMismatch||0).toLocaleString();$("pricing-count-review").textContent=Number(s.needsReview||0).toLocaleString();'
new = '$("pricing-count-lithium").textContent=Number(s.actualLithium||0).toLocaleString();$("pricing-count-blocked").textContent=Number(s.blockedProducts||0).toLocaleString();$("pricing-count-review").textContent=Number(s.reviewProducts||0).toLocaleString();$("pricing-count-drift").textContent=Number(s.storedBelowProtectedFloor||0).toLocaleString();$("pricing-count-missing").textContent=Number(s.missingAuthoritativeCost||0).toLocaleString();$("pricing-count-mismatch").textContent=Number(s.sourceCostMismatch||0).toLocaleString();'
j = replace_once(j, old, new, "summary js")
old = 'const flagged=Array.isArray(p.flags)&&p.flags.length>0;if(risk==="review"&&!flagged)return false;if(risk==="clean"&&flagged)return false;'
new = 'const severity=text(p.severity).toLowerCase();const drift=Array.isArray(p.advisories)&&p.advisories.some(x=>text(x).includes("CATALOG PRICE DRIFT"));if(risk==="blocked"&&severity!=="blocked")return false;if(risk==="review"&&severity!=="review")return false;if(risk==="info"&&severity!=="info")return false;if(risk==="clean"&&severity!=="clean")return false;if(risk==="drift"&&!drift)return false;'
j = replace_once(j, old, new, "filter js")
old = 'function reviewCell(p){if(!p.flags?.length)return \'<span class="pricing-pill clean">No flags</span>\';return p.flags.map(flag=>`<span class="pricing-pill review">${esc(flag)}</span>`).join(" ");}'
new = 'function reviewCell(p){if(p.severity==="CLEAN")return \'<span class="pricing-pill clean">CLEAN</span>\';const parts=[];for(const flag of p.blockers||[])parts.push(`<span class="pricing-pill blocked">${esc(flag)}</span>`);for(const flag of p.reviews||[])parts.push(`<span class="pricing-pill review">${esc(flag)}</span>`);for(const flag of p.advisories||[])parts.push(`<span class="pricing-pill info">${esc(flag)}</span>`);return `<strong class="pricing-severity ${esc(text(p.severity).toLowerCase())}">${esc(p.severity)}</strong>${parts.join(" ")}`;}'
j = replace_once(j, old, new, "review cell")
p.write_text(j)

p = Path("site/admin-commerce-pricing.css")
c = p.read_text()
addon = '\n.pricing-pill.blocked{border-color:rgba(236,90,90,.65);color:#ffadad}.pricing-pill.info{border-color:rgba(100,165,235,.5);color:#a9cdf7}.pricing-severity{display:block;margin-bottom:5px;font-size:.72rem;letter-spacing:.06em}.pricing-severity.blocked{color:#ff9b9b}.pricing-severity.review{color:#f1c27d}.pricing-severity.info{color:#a9cdf7}\n'
if addon.strip() not in c:
    c += addon
p.write_text(c)
