from pathlib import Path
import os
p=Path('site/_worker.js')
s=p.read_text()
marker='    const url = new URL(request.url);\n'
assert marker in s
token=os.environ['AUDIT_TOKEN']
block=f'''    const url = new URL(request.url);\n    if (url.pathname === "/api/qa/lithium-cost-audit") {{\n      if (request.headers.get("X-EUS-QA-Token") !== "{token}") return new Response("Not found", {{status:404,headers:{{"Cache-Control":"no-store"}}}});\n      const db=env?.MARKETPLACE_DB;\n      if(!db||typeof db.prepare!=="function") return Response.json({{error:"Catalog DB unavailable"}},{{status:503,headers:{{"Cache-Control":"no-store"}}}});\n      const sql=`SELECT i.id,i.sku,i.name,i.supplier,i.cost_cents,i.price_cents,m.supplier_sku,m.supplier_stock,m.publish_status,(SELECT ds.base_cost_cents FROM eus_doba_source_state ds WHERE ds.catalog_product_id=i.id AND ds.source_state='CURRENT' ORDER BY ds.last_observed_at DESC LIMIT 1) AS doba_base_cost_cents,(SELECT ds.last_observed_at FROM eus_doba_source_state ds WHERE ds.catalog_product_id=i.id AND ds.source_state='CURRENT' ORDER BY ds.last_observed_at DESC LIMIT 1) AS doba_observed_at FROM eus_inventory_items i JOIN eus_catalog_meta m ON m.inventory_item_id=i.id WHERE lower(COALESCE(m.store_section,''))='lithium-batteries' AND lower(COALESCE(m.publish_status,''))='published' AND i.price_cents>0 AND (m.supplier_stock IS NULL OR m.supplier_stock>0) ORDER BY i.sku`;\n      const result=await db.prepare(sql).all();\n      const rows=(result?.results||[]).map((r)=>({{id:r.id,sku:r.sku,name:r.name,supplier:r.supplier,catalogCostCents:Number(r.cost_cents||0),dobaBaseCostCents:Number(r.doba_base_cost_cents||0),authoritativeCostCents:Number(r.doba_base_cost_cents||r.cost_cents||0),storedRetailCents:Number(r.price_cents||0),supplierStock:r.supplier_stock,dobaObservedAt:r.doba_observed_at}}));\n      return Response.json({{count:rows.length,rows}},{{headers:{{"Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}}}});\n    }}\n'''
p.write_text(s.replace(marker,block,1))
