import { chromium } from 'playwright';
import fs from 'node:fs';
const base=(process.env.BASE||'').replace(/\/$/,'');
if(!base)throw new Error('BASE required');
const audit=JSON.parse(fs.readFileSync(process.env.COST_AUDIT||'/tmp/cost-audit/lithium-pricing-audit-sanitized.json','utf8'));
const costs=Array.isArray(audit.products)?audit.products:[];
if(costs.length!==38)throw new Error(`cost rows ${costs.length}`);
const costById=new Map(costs.map(x=>[String(x.id),x]));
const browser=await chromium.launch({headless:true});
const out={base};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const decodeEntities=s=>String(s).replaceAll('&amp;','&').replaceAll('&#39;',"'").replaceAll('&quot;','"');
async function json(url,opts={},tries=6){let last;for(let i=0;i<tries;i++){try{const r=await fetch(url,opts);const t=await r.text();if(!r.ok)throw new Error(`${r.status} ${t.slice(0,180)}`);return JSON.parse(t);}catch(e){last=e;await sleep(1000);}}throw last;}
async function ov(p){return p.evaluate(()=>Math.max(0,document.documentElement.scrollWidth-document.documentElement.clientWidth));}
async function imgDecode(p,src){return p.evaluate(async s=>new Promise(resolve=>{const i=new Image();i.onload=()=>resolve({ok:true,w:i.naturalWidth,h:i.naturalHeight});i.onerror=()=>resolve({ok:false,w:0,h:0});i.src=s;}),src);}
try{
  const homeSource=decodeEntities(await (await fetch(base+'/')).text());
  for(const s of ['Shop Current Products','Featured products from our Lithium and RV & Outdoor stores.','Hawaii Lithium Batteries'])if(!homeSource.includes(s))throw new Error(`home source missing ${s}`);
  const startSource=decodeEntities(await (await fetch(base+'/start-a-project')).text()).toLowerCase();
  for(const s of ['underlying project families','intake intent tells management','management review'])if(startSource.includes(s))throw new Error(`start source jargon ${s}`);

  const home=await browser.newPage({viewport:{width:1440,height:1000}});let r=await home.goto(base+'/',{waitUntil:'domcontentloaded',timeout:60000});if(!r?.ok())throw new Error(`home ${r?.status()}`);
  const homeText=await home.locator('body').innerText();for(const s of ['Shop Current Products','Featured products from our Lithium and RV & Outdoor stores.','Hawaii Lithium Batteries'])if(!homeText.includes(s))throw new Error(`home rendered missing ${s}`);
  const route=home.locator('.hc-route[style*="homepage-option-2-lithium-solar.webp"]').first();if(await route.count()!==1)throw new Error('option2 route missing');
  const routeBox=await route.boundingBox();const bg=await route.evaluate(el=>getComputedStyle(el,'::before').backgroundImage);const option2=await imgDecode(home,'/assets/homepage-option-2-lithium-solar.webp');
  if(!routeBox||routeBox.width<100||routeBox.height<80||!bg.includes('homepage-option-2-lithium-solar.webp')||!option2.ok||option2.w!==960||option2.h!==540)throw new Error(`option2 render ${JSON.stringify({routeBox,bg,option2})}`);
  const o3=home.locator('img[src="/assets/homepage-option-3-home-rv-lifestyle.webp"]').first();if(await o3.count()!==1)throw new Error('option3 element missing');await o3.scrollIntoViewIfNeeded();await home.waitForFunction(()=>{const i=document.querySelector('img[src="/assets/homepage-option-3-home-rv-lifestyle.webp"]');return i?.complete&&i.naturalWidth>0;},{timeout:15000});const option3=await o3.evaluate(i=>({ok:i.complete&&i.naturalWidth>0,w:i.naturalWidth,h:i.naturalHeight,bw:i.getBoundingClientRect().width,bh:i.getBoundingClientRect().height}));if(!option3.ok||option3.w!==960||option3.h!==540||option3.bw<100||option3.bh<50)throw new Error(`option3 render ${JSON.stringify(option3)}`);
  await home.locator('[data-home-commerce]').scrollIntoViewIfNeeded();await home.waitForFunction(()=>document.querySelectorAll('[data-home-products="lithium"] article').length===4&&document.querySelectorAll('[data-home-products="rv"] article').length===4,{timeout:20000});const homeOv=await ov(home);if(homeOv>2)throw new Error(`home overflow ${homeOv}`);out.home={copy:true,hawaiiLabel:true,featuredLithium:4,featuredRv:4,option2,option3,overflow:homeOv};await home.close();

  const sp=await browser.newPage({viewport:{width:1280,height:900}});r=await sp.goto(base+'/start-a-project',{waitUntil:'domcontentloaded',timeout:60000});if(!r?.ok())throw new Error(`start ${r?.status()}`);const st=(await sp.locator('body').innerText()).toLowerCase();for(const s of ['underlying project families','intake intent','management review'])if(st.includes(s))throw new Error(`rendered start jargon ${s}`);if(!st.includes('pick the closest match'))throw new Error('clean start copy missing');out.startProject={status:r.status(),jargonFree:true};await sp.close();

  const cat=await json(base+'/api/store/catalog?section=lithium-batteries');const products=(cat.products||[]).filter(p=>Number(p.priceCents)>0);if(products.length!==38)throw new Error(`catalog ${products.length}`);const known='cat-01e78438-5fb8-4e0d-aaab-ffbe86f5cf77';const knownProduct=products.find(p=>String(p.id)===known)||products.find(p=>/100\s*ah/i.test(String(p.title||'')))||products[0];

  const flow=await browser.newPage({viewport:{width:1280,height:900}});r=await flow.goto(base+'/lithium-batteries',{waitUntil:'domcontentloaded',timeout:60000});if(!r?.ok())throw new Error(`lithium ${r?.status()}`);await flow.waitForSelector('.lithium-card',{timeout:30000});const lc=await flow.locator('.lithium-card').count();if(lc!==38)throw new Error(`lithium cards ${lc}`);const hiLink=flow.locator('a[href="/hawaii-lithium-batteries"]').first();if(await hiLink.count()!==1)throw new Error('Lithium→Hawaii link missing');await hiLink.click({force:true});await flow.waitForURL(/\/hawaii-lithium-batteries/,{timeout:20000});await flow.waitForSelector('.lithium-card',{timeout:30000});await flow.waitForTimeout(1800);const hc=await flow.locator('.lithium-card').count();const nonBattery=await flow.locator('.lithium-card[data-hawaii-battery-units="0"]').count();if(hc!==31||nonBattery!==0)throw new Error(`Hawaii cards ${hc} nonbattery ${nonBattery}`);let card=flow.locator(`.lithium-card[data-product-id="${knownProduct.id}"]`).first();if(await card.count()!==1)card=flow.locator('.lithium-card').first();const smokeId=await card.getAttribute('data-product-id');const checkoutUrl=await card.locator('[data-hawaii-action]').getAttribute('data-checkout-url');if(!smokeId||!checkoutUrl?.startsWith('/checkout/'))throw new Error(`Hawaii checkout URL ${checkoutUrl}`);out.flow={lithiumCards:lc,hawaiiCards:hc,nonBattery,smokeProduct:smokeId,checkoutUrl};await flow.close();

  let floors=0,coupons=0;for(const p of products){const c=costById.get(String(p.id));if(!c)throw new Error(`cost missing ${p.id}`);const payload={source:'lithium',id:p.id,name:p.title||p.name||'Lithium item',quantity:1,couponCode:'LABORDAY25',shipping:{state:'CO'}};const q=await json(base+'/api/store-checkout/quote',{method:'POST',headers:{'Content-Type':'application/json','Origin':base},body:JSON.stringify(payload)});if(Number(q.merchandiseCents)<Number(c.requiredPromoFloorCents||0))floors++;if(Number(c.authoritativeCostCents||0)>0&&Number(q.couponPercent||0)!==25)coupons++;}if(floors||coupons)throw new Error(`promotion floor=${floors} coupon=${coupons}`);
  const smoke=products.find(p=>String(p.id)===String(smokeId))||knownProduct;const payload={source:'lithium',id:smoke.id,name:smoke.title||'Lithium Battery',quantity:1,couponCode:'LABORDAY25'};const opts=x=>({method:'POST',headers:{'Content-Type':'application/json','Origin':base},body:JSON.stringify({...payload,shipping:{state:x}})});const co=await json(base+'/api/store-checkout/quote',opts('CO'));const hi=await json(base+'/api/store-checkout/quote',opts('HI'));if(Number(co.shippingCents)!==2799)throw new Error(`Lower48 ${co.shippingCents}`);if(Number(hi.hawaii?.customerFreightPerBatteryCents)!==9900)throw new Error(`HI freight ${hi.hawaii?.customerFreightPerBatteryCents}`);if(Number(hi.couponPercent||0)!==25)throw new Error(`HI coupon ${hi.couponPercent}`);if(hi.promotion?.shippingDiscounted!==false)throw new Error('freight discounted');if(Number(hi.hawaii?.pickupPriceCents)!==Number(hi.merchandiseCents)+Number(hi.hawaii?.pickupFreightCents))throw new Error('pickup promotion math');if(hi.hawaii?.customerState!=='review_required'||hi.hawaii?.paymentAllowed!==false||Number(hi.shippingCents)!==0)throw new Error(`HI gate ${hi.hawaii?.customerState}/${hi.hawaii?.paymentAllowed}/${hi.shippingCents}`);out.promotion={productsAudited:38,floorFailures:0,couponFailures:0,couponPercent:hi.couponPercent,freightDiscounted:hi.promotion?.shippingDiscounted};out.shipping={lower48ShippingCents:co.shippingCents,hawaiiFreightPerBatteryCents:hi.hawaii?.customerFreightPerBatteryCents,merchandiseCents:hi.merchandiseCents,pickupFreightCents:hi.hawaii?.pickupFreightCents,pickupPriceCents:hi.hawaii?.pickupPriceCents,state:hi.hawaii?.customerState,paymentAllowed:hi.hawaii?.paymentAllowed};

  const ck=await browser.newPage({viewport:{width:1280,height:900}});r=await ck.goto(base+checkoutUrl,{waitUntil:'domcontentloaded',timeout:60000});if(!r?.ok())throw new Error(`checkout ${r?.status()}`);await ck.waitForSelector('#checkout-hawaii-freight:not([hidden])',{timeout:20000});await ck.waitForFunction(()=>/Freight Review Required/i.test(document.querySelector('#checkout-hawaii-state')?.textContent||''),{timeout:20000});const paypalHidden=await ck.locator('#checkout-paypal').evaluate(e=>e.hidden),reserveHidden=await ck.locator('#checkout-hawaii-reserve').evaluate(e=>e.hidden);if(!paypalHidden||reserveHidden)throw new Error(`PayPal gate ${paypalHidden}/${reserveHidden}`);out.checkout={state:(await ck.locator('#checkout-hawaii-state').innerText()).trim(),paypalHidden,reserveHidden,pickupPrice:(await ck.locator('#checkout-hawaii-pickup-price').innerText()).trim()};await ck.close();

  const footerPaths=['/','/store','/rv-store','/lithium-batteries','/hawaii-lithium-batteries',`/product?id=${encodeURIComponent(smoke.id)}&store=lithium`,checkoutUrl];const verified=[];for(const path of footerPaths){const p=await browser.newPage({viewport:{width:1100,height:800}});r=await p.goto(base+path,{waitUntil:'domcontentloaded',timeout:60000});if(!r?.ok())throw new Error(`footer ${path} ${r?.status()}`);const link=p.locator('footer a[href="/terms"]').first();if(await link.count()!==1)throw new Error(`Terms link missing ${path}`);verified.push(path);await p.close();}const terms=await browser.newPage();r=await terms.goto(base+'/terms',{waitUntil:'domcontentloaded',timeout:60000});if(!r?.ok())throw new Error(`terms ${r?.status()}`);out.terms={status:r.status(),footerPaths:verified};await terms.close();

  for(const [name,path] of [['mobileHome','/'],['mobileHawaii','/hawaii-lithium-batteries']]){const p=await browser.newPage({viewport:{width:390,height:844}});r=await p.goto(base+path,{waitUntil:'domcontentloaded',timeout:60000});if(!r?.ok())throw new Error(`${name} ${r?.status()}`);await p.waitForTimeout(1600);const x=await ov(p);if(x>2)throw new Error(`${name} overflow ${x}`);out[name]={overflow:x};await p.close();}
  console.log(JSON.stringify(out,null,2));
}finally{await browser.close();}
