from pathlib import Path
import json,re,sys
repo=Path(sys.argv[1]).resolve()

def replace(path,old,new,count=1):
    p=repo/path;text=p.read_text()
    if text.count(old)<count: raise SystemExit(f"missing anchor {path}: {old[:100]!r}")
    p.write_text(text.replace(old,new,count))

def regex(path,pat,repl,count=1,flags=0):
    p=repo/path;text=p.read_text();new,n=re.subn(pat,repl,text,count=count,flags=flags)
    if n!=count: raise SystemExit(f"regex failed {path}: {pat!r} => {n}")
    p.write_text(new)

# Existing SOK runtime: expose the established schema initializer to the availability extension.
p=repo/'site/sok-operations-runtime.js';text=p.read_text()
if 'ensureSokOperationsSchema' not in text:
    text += '\nexport { ensureSchema as ensureSokOperationsSchema };\n'
p.write_text(text)

# Worker integration: unified catalog projection, public reservation path, protected admin, private runtime.
replace('site/_worker.js','import { handleSokOperationsAdminApi, handleSokOperationsPublicApi, filterHawaiiEligibleCatalogProducts } from "./sok-operations-runtime.js";','import { handleSokOperationsAdminApi, handleSokOperationsPublicApi, filterHawaiiEligibleCatalogProducts } from "./sok-operations-runtime.js";\nimport { handleSokAvailabilityPublicApi, handleSokAvailabilityAdminApi, publicSokCatalogProducts } from "./sok-availability-runtime.js";')
p=repo/'site/_worker.js';text=p.read_text()
text=text.replace('"/sok-operations-runtime.js",','"/sok-operations-runtime.js",\n      "/sok-availability-runtime.js",')
text=text.replace('"/hawaii-lithium-runtime.js","/sok-operations-runtime.js","/sync-admin-runtime.js"','"/hawaii-lithium-runtime.js","/sok-operations-runtime.js","/sok-availability-runtime.js","/sync-admin-runtime.js"')
p.write_text(text)
replace('site/_worker.js','function checkoutJson(data,status){return Response.json(data,{status,headers:{"Cache-Control":"no-store","X-Content-Type-Options":"nosniff","X-Frame-Options":"DENY","Referrer-Policy":"no-referrer"}});}','function checkoutJson(data,status){return Response.json(data,{status,headers:{"Cache-Control":"no-store","X-Content-Type-Options":"nosniff","X-Frame-Options":"DENY","Referrer-Policy":"no-referrer"}});}\nasync function mergedCatalogPublicApi(request,env,pathname){const response=await handleCatalogPublicApi(request,env,pathname);if(!response?.ok)return response;try{const url=new URL(request.url);if(clean(url.searchParams.get("section"),60).toLowerCase()!=="lithium-batteries")return response;const data=await response.json();const sok=await publicSokCatalogProducts(env);const existing=Array.isArray(data?.products)?data.products:[];const keys=new Set(sok.flatMap(p=>[clean(p.id,140).toLowerCase(),clean(p.sku,140).toLowerCase()]));const products=[...sok,...existing.filter(p=>!keys.has(clean(p?.id,140).toLowerCase())&&!keys.has(clean(p?.sku,140).toLowerCase()))];return Response.json({...data,products,count:products.length},{status:200,headers:{"Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}});}catch(_){return response;}}')
old='async function getPublicCatalog(request,env,section){try{const isLithium=section==="lithium"||section==="hawaii";const path=isLithium?"/api/store/catalog?section=lithium-batteries":"/api/store-catalog?section=rv-outdoor";const apiUrl=new URL(path,request.url);const apiRequest=new Request(apiUrl.toString(),{method:"GET",headers:{Accept:"application/json"}});const response=await handleCatalogPublicApi(apiRequest,env,apiUrl.pathname);if(!response?.ok)return[];const data=await response.json().catch(()=>({}));const rows=publicRows(data,section==="rv"?"rv":section);return section==="hawaii"?await filterHawaiiEligibleCatalogProducts(env,rows):rows;}catch(_){return[];}}'
new='async function getPublicCatalog(request,env,section){try{const isLithium=section==="lithium"||section==="hawaii";const path=isLithium?"/api/store/catalog?section=lithium-batteries":"/api/store-catalog?section=rv-outdoor";const apiUrl=new URL(path,request.url);const apiRequest=new Request(apiUrl.toString(),{method:"GET",headers:{Accept:"application/json"}});const response=await handleCatalogPublicApi(apiRequest,env,apiUrl.pathname);if(!response?.ok)return[];const data=await response.json().catch(()=>({}));const rows=publicRows(data,section==="rv"?"rv":section);if(!isLithium)return rows;const sok=await publicSokCatalogProducts(env);const approved=section==="hawaii"?await filterHawaiiEligibleCatalogProducts(env,rows):rows;const keys=new Set(sok.flatMap(p=>[clean(p.id,140).toLowerCase(),clean(p.sku,140).toLowerCase()]));return [...sok,...approved.filter(p=>!keys.has(clean(p?.id,140).toLowerCase())&&!keys.has(clean(p?.sku,140).toLowerCase()))];}catch(_){return[];}}'
replace('site/_worker.js',old,new)
replace('site/_worker.js','if(url.pathname==="/api/store-catalog"||url.pathname==="/api/store/catalog") return handleCatalogPublicApi(request,env,url.pathname);','if(url.pathname==="/api/store-catalog"||url.pathname==="/api/store/catalog") return mergedCatalogPublicApi(request,env,url.pathname);\n    if(url.pathname==="/api/sok/catalog"||url.pathname==="/api/sok/reservations") return handleSokAvailabilityPublicApi(request,env,url.pathname);')
replace('site/_worker.js','if(url.pathname==="/api/admin/sok-operations"||url.pathname.startsWith("/api/admin/sok-operations/")) return handleSokOperationsAdminApi(request,env,url.pathname);','if(url.pathname==="/api/admin/sok-operations"||url.pathname.startsWith("/api/admin/sok-operations/")) return handleSokOperationsAdminApi(request,env,url.pathname);\n    if(url.pathname==="/api/admin/sok-availability"||url.pathname.startsWith("/api/admin/sok-availability/")) return handleSokAvailabilityAdminApi(request,env,url.pathname);')

# Route the new private runtime through the Worker so direct requests resolve to 404.
p=repo/'site/_routes.json';data=json.loads(p.read_text());inc=data.setdefault('include',[])
if '/sok-availability-runtime.js' not in inc: inc.append('/sok-availability-runtime.js')
p.write_text(json.dumps(data,indent=2)+"\n")

# Lithium storefront: merge the SOK projection into the unified catalog and render availability modes.
replace('site/lithium-shop.js','  function card(product, index = 0) {','  function commerceFor(product) {\n    const mode=String(product?.availabilityMode||"available").toLowerCase();\n    const label=product?.commerceLabel||(mode==="prepurchase"?"PRE-PURCHASE":mode==="backorder"?"AVAILABLE ON BACKORDER":mode==="unavailable"?"TEMPORARILY UNAVAILABLE":"AVAILABLE");\n    const cta=product?.commerceCta||(mode==="prepurchase"?"Pre-Purchase":mode==="backorder"?"Available on Backorder":mode==="unavailable"?"Check Availability":"Buy Now");\n    return {mode,label,cta,paymentEligible:product?.paymentEligible!==false,reservationUrl:String(product?.reservationUrl||"").trim(),timing:String(product?.customerTimingNotice||"").trim(),window:String(product?.expectedShipWindow||product?.expectedAvailableDate||"").trim()};\n  }\n\n  function card(product, index = 0) {')
replace('site/lithium-shop.js','    const reviewUrl = `/hawaii-lithium-batteries?productId=${encodeURIComponent(id)}&product=${encodeURIComponent(view.rawTitle || view.title)}&qty=1#hawaii-request`;\n    const inventory = String(product.availabilityStatus || "check").toLowerCase() === "available" ? "Available" : "Availability confirmed before order";','    const reviewUrl = `/hawaii-lithium-batteries?productId=${encodeURIComponent(id)}&product=${encodeURIComponent(view.rawTitle || view.title)}&qty=1#hawaii-request`;\n    const commerce=commerceFor(product);\n    const reservationUrl=commerce.reservationUrl||`/sok-order.html?sku=${encodeURIComponent(sku)}&mode=${encodeURIComponent(commerce.mode)}`;\n    const normalActionUrl=commerce.paymentEligible?checkoutUrl:reservationUrl;\n    const normalActionLabel=commerce.cta;\n    const inventory = product?.sokProduct ? commerce.label : (String(product.availabilityStatus || "check").toLowerCase() === "available" ? "Available" : "Availability confirmed before order");')
replace('site/lithium-shop.js','        <div class="lithium-card__shipping ${status.className}" data-hawaii-status>${esc(status.label)}</div>','        <div class="lithium-card__shipping ${status.className}" data-hawaii-status>${esc(status.label)}</div>\n        ${!hawaiiMode && product?.sokProduct ? `<p class="lithium-card__spec-line"><strong>${esc(commerce.label)}</strong>${commerce.window ? ` · ${esc(commerce.window)}` : ""}</p>${commerce.mode === "prepurchase" || commerce.mode === "backorder" ? `<p class="lithium-card__spec-line">${esc(commerce.timing || "Expected fulfillment timing is an estimate and may change.")}</p>` : ""}` : ""}')
replace('site/lithium-shop.js','${hawaiiMode ? "Check Hawaii Availability" : "Buy Now"}</a></div></div>','${hawaiiMode ? "Check Hawaii Availability" : esc(normalActionLabel)}</a></div></div>')
replace('site/lithium-shop.js','${hawaiiMode ? `data-hawaii-action data-checkout-url="${esc(checkoutUrl)}" data-review-url="${esc(reviewUrl)}" href="${esc(reviewUrl)}"` : `href="${esc(checkoutUrl)}"`}>','${hawaiiMode ? `data-hawaii-action data-checkout-url="${esc(checkoutUrl)}" data-review-url="${esc(reviewUrl)}" href="${esc(reviewUrl)}"` : `href="${esc(normalActionUrl)}"`}>')
replace('site/lithium-shop.js','    let products = data.products;\n    if (hawaiiMode) {','    let products = data.products;\n    try { const sokResponse=await fetch("/api/sok/catalog",{headers:{Accept:"application/json"},cache:"no-store"}); const sokData=await sokResponse.json().catch(()=>({})); if(sokResponse.ok&&Array.isArray(sokData.products)){ const keys=new Set(sokData.products.flatMap(p=>[String(p.id||"").toLowerCase(),String(p.sku||"").toLowerCase()])); products=[...sokData.products,...products.filter(p=>!keys.has(String(p.id||"").toLowerCase())&&!keys.has(String(p.sku||"").toLowerCase()))]; } } catch (_) {}\n    if (hawaiiMode) {')
replace('site/lithium-shop.js','      products = eligibilityResponse.ok ? products.filter((product) => allowedIds.has(String(product.id || "").trim()) || allowedSkus.has(String(product.sku || "").trim().toUpperCase())) : [];','      products = eligibilityResponse.ok ? products.filter((product) => product?.sokProduct || allowedIds.has(String(product.id || "").trim()) || allowedSkus.has(String(product.sku || "").trim().toUpperCase())) : products.filter((product)=>product?.sokProduct);')
replace('site/lithium-shop.js','      render(rows);','      render(rows);\n      if (hawaiiMode) syncHawaiiStatuses();',1)
replace('site/lithium-shop.js','      if (hawaiiMode) { hydrateDeferredImages(grid); syncHawaiiStatuses(); }\n      return;','      if (hawaiiMode) { hydrateDeferredImages(grid); syncHawaiiStatuses(); }\n      hydrateAndRender();\n      return;')

# Checkout server understands SOK as a real lithium source while keeping Hawaii gates authoritative.
replace('site/store-checkout-server.js','import { evaluateSokHawaiiOrder } from "./sok-operations-runtime.js";','import { evaluateSokHawaiiOrder } from "./sok-operations-runtime.js";\nimport { getSokCheckoutEntry } from "./sok-availability-runtime.js";')
replace('site/store-checkout-server.js','  const source = clean(raw?.source,20).toLowerCase() === "lithium" ? "lithium" : "rv";\n  const catalogEntry = await catalogRvEntry(env, id);','  const source = clean(raw?.source,20).toLowerCase() === "lithium" ? "lithium" : "rv";\n  const destinationState = clean(raw?.shipping?.state, 2).toUpperCase();\n  const catalogEntry = await catalogRvEntry(env, id) || (source === "lithium" ? await getSokCheckoutEntry(env,id,destinationState) : null);')
replace('site/store-checkout-server.js','  const destinationState = clean(raw?.shipping?.state, 2).toUpperCase();\n  const blockedStates =','  const blockedStates =')
replace('site/store-checkout-server.js','  if (entry.shippingVerified !== true) return {ok:false,status:409,...fallback,error:"Doba shipping is not verified for this item"};','  if (entry.shippingVerified !== true) return {ok:false,status:409,...fallback,error:"Shipping is not verified for this item"};')
replace('site/store-checkout-server.js','  const config = await getPromotionConfig(env);\n  const priced = pricingForProduct(product, config);','  const config = await getPromotionConfig(env);\n  const priced = pricingForProduct(product, config);\n  const availability = entry.sokAvailability || null;')
replace('site/store-checkout-server.js','    ok:true,source,id,productName:clean(entry.name||raw?.name,240)||(source==="lithium"?"Lithium item":"RV & Outdoor item"),productImage:clean(entry.imageUrl||entry.image,1200),quantity:qty,','    ok:true,source,id,productName:clean(entry.name||raw?.name,240)||(source==="lithium"?"Lithium item":"RV & Outdoor item"),productImage:clean(entry.imageUrl||entry.image,1200),quantity:qty,\n    availability:availability?{...availability,reservationUrl:`/sok-order.html?sku=${encodeURIComponent(hawaiiSku||product?.sku||"")}&mode=${encodeURIComponent(availability.mode||"unavailable")}&qty=${qty}${destinationState?`&state=${encodeURIComponent(destinationState)}`:""}`} : null,')
replace('site/store-checkout-server.js','  if (!quote.ok) return json(quote, quote.status || 400);\n  if (quote.hawaii?.customerState === "review_required")','  if (!quote.ok) return json(quote, quote.status || 400);\n  if (quote.availability?.paymentEligible === false) return json({error:quote.availability?.mode==="prepurchase"?"Pre-Purchase timing must be confirmed before payment.":quote.availability?.mode==="backorder"?"Backorder replenishment and timing must be confirmed before payment.":"This item is not currently eligible for payment.",reservationRequired:true,reservationUrl:quote.availability?.reservationUrl,quote},409);\n  if (quote.availability?.requiresTimingAcknowledgement && raw?.availabilityTimingAcknowledged !== true) return json({error:"Please acknowledge the estimated fulfillment timing before payment.",timingAcknowledgementRequired:true,quote},409);\n  if (quote.hawaii?.customerState === "review_required")')
replace('site/store-checkout-server.js','JSON.stringify({...quote.doba,shippingRule:quote.shippingRule||{},hawaii:quote.hawaii||null,promotion:{','JSON.stringify({...quote.doba,shippingRule:quote.shippingRule||{},hawaii:quote.hawaii||null,availability:quote.availability||null,promotion:{')

# Checkout UI: explicit timing disclosure and acknowledgment before PayPal for paid pre-purchase/backorder.
replace('site/checkout/index.html','<script defer src="/store-checkout.js?v=4.5.3"></script>','<script defer src="/store-checkout.js?v=4.6.1"></script>')
replace('site/checkout/index.html','        <div id="checkout-status" class="eus-checkout-status" role="status">Loading checkout…</div>','        <section id="checkout-availability-panel" class="eus-checkout-hawaii" hidden><p class="eus-checkout-step">PRODUCT AVAILABILITY</p><h3 id="checkout-availability-label">Availability</h3><p id="checkout-availability-timing"></p><p>Item may not be immediately available. Estimated fulfillment timing may change. Elevation will provide status updates and normal cancellation/refund terms remain applicable to the transaction.</p><label id="checkout-availability-ack-row" hidden><input id="checkout-availability-ack" type="checkbox"> I understand the fulfillment timing is an estimate and may change.</label><a id="checkout-availability-reserve" class="eus-checkout-hawaii-cta" href="/sok-order.html">Start Reservation / Order Review</a></section>\n\n        <div id="checkout-status" class="eus-checkout-status" role="status">Loading checkout…</div>')
replace('site/store-checkout.js','  const hawaiiNext = document.querySelector("#checkout-hawaii-next");','  const hawaiiNext = document.querySelector("#checkout-hawaii-next");\n  const availabilityPanel=document.querySelector("#checkout-availability-panel");\n  const availabilityLabel=document.querySelector("#checkout-availability-label");\n  const availabilityTiming=document.querySelector("#checkout-availability-timing");\n  const availabilityAckRow=document.querySelector("#checkout-availability-ack-row");\n  const availabilityAck=document.querySelector("#checkout-availability-ack");\n  const availabilityReserve=document.querySelector("#checkout-availability-reserve");')
replace('site/store-checkout.js','    couponCode: couponCodeEl?.value.trim() || "",','    couponCode: couponCodeEl?.value.trim() || "",\n    availabilityTimingAcknowledged: Boolean(availabilityAck?.checked),')
replace('site/store-checkout.js','  const formReady = () => {\n    const address = shipping();','  const formReady = () => {\n    if (quote?.availability?.requiresTimingAcknowledgement && !availabilityAck?.checked) return false;\n    const address = shipping();')
replace('site/store-checkout.js','    setProductImage(next.productImage, productName);','    if(availabilityPanel){const a=next.availability||null;availabilityPanel.hidden=!a||a.mode==="available";if(a){availabilityLabel.textContent=a.label||"Product Availability";availabilityTiming.textContent=[a.expectedShipWindow||a.expectedAvailableDate||"",a.timingNotice||""].filter(Boolean).join(" — ");availabilityAckRow.hidden=!a.requiresTimingAcknowledgement;availabilityReserve.href=a.reservationUrl||"/sok-order.html";availabilityReserve.hidden=Boolean(a.paymentEligible);if(!a.paymentEligible)paypalEl.hidden=true;}}\n    setProductImage(next.productImage, productName);')
replace('site/store-checkout.js','    else setStatus(config?.configured ? "Secure PayPal checkout ready." : "Order details loaded.", config?.configured ? "ready" : "");','    else if(body.availability && body.availability.paymentEligible===false) setStatus(`${body.availability.label||"Product review required"}. Start the reservation/order review to continue; no payment will be collected yet.`,"ready");\n    else if(body.availability && ["prepurchase","backorder"].includes(String(body.availability.mode||""))) setStatus(`${body.availability.label}. Review and acknowledge the estimated fulfillment timing before payment.`,"ready");\n    else setStatus(config?.configured ? "Secure PayPal checkout ready." : "Order details loaded.", config?.configured ? "ready" : "");')

# Admin: availability controls and carrier package visibility.
replace('site/admin-sok.html','<script defer src="/admin-sok.js"></script>','<script defer src="/admin-sok.js"></script><script defer src="/admin-sok-availability.js?v=4.6.1"></script>')
replace('site/admin-sok.html','</main></body></html>','<section id="sok-availability-admin"><p>Loading SOK availability controls…</p></section></main></body></html>')

# Hawaii customer page: visible SOK catalog + freight-review framing, not only already-cleared products.
p=repo/'site/hawaii-lithium-batteries.html';h=p.read_text();h=h.replace('Hawaii-Eligible Battery List','Hawaii SOK Battery Catalog');h=h.replace('Only battery models approved for the Hawaii freight workflow appear here.','SOK battery models can be reviewed here before freight qualification is complete. Products that are not yet carrier/economics approved remain Freight Review Required and cannot proceed to payment.');p.write_text(h)

print('SOK pre-purchase/backorder patch applied')
