export const catalogStyles = `
.catalog-main{min-height:55vh;background:#f4f7f8;color:#0b1b22;padding:3rem 0 4rem}
.catalog-shell{width:min(1180px,calc(100% - 2rem));margin:0 auto}
.catalog-hero{display:grid;gap:.8rem;margin-bottom:2rem}.catalog-hero h1{font-size:clamp(2rem,5vw,4rem);line-height:1;margin:0;color:#07161c}.catalog-hero p{max-width:780px;margin:0;color:#49616b;line-height:1.65}
.catalog-filter{display:flex;flex-wrap:wrap;gap:.65rem;margin:1.25rem 0 2rem}.catalog-filter a{display:inline-flex;padding:.65rem .9rem;border:1px solid #c7d4d9;border-radius:999px;color:#16333e;text-decoration:none;background:#fff}.catalog-filter a[aria-current="page"]{border-color:#16333e;font-weight:700}
.catalog-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem}.catalog-card{background:#fff;border:1px solid #d9e3e6;border-radius:16px;padding:1.2rem;display:flex;flex-direction:column;gap:.7rem;box-shadow:0 8px 26px rgba(4,25,32,.06)}.catalog-card h2,.catalog-card h3{margin:0;color:#07161c}.catalog-card .sku{font:600 .78rem/1.3 ui-monospace,SFMono-Regular,Menlo,monospace;color:#607780;word-break:break-word}.catalog-card .vendor{font-size:.78rem;font-weight:800;letter-spacing:.08em;text-transform:uppercase;color:#38606d}.catalog-card .price{font-size:1.25rem;font-weight:800;color:#07161c}.catalog-card .status{padding:.65rem .75rem;border-radius:10px;background:#fff5db;color:#6a4b00;font-size:.86rem;font-weight:700}.catalog-card a{margin-top:auto;color:#0a5568;font-weight:800;text-decoration:none}
.catalog-empty{padding:2rem;border:1px dashed #aebfc5;border-radius:14px;background:#fff;color:#425b65}.catalog-detail{display:grid;grid-template-columns:minmax(0,1fr) minmax(300px,.7fr);gap:2rem;align-items:start}.catalog-detail-card,.catalog-facts{background:#fff;border:1px solid #d9e3e6;border-radius:16px;padding:1.4rem}.catalog-detail-card h1{margin:.3rem 0 .8rem;font-size:clamp(1.8rem,4vw,3rem)}.catalog-facts dl{display:grid;grid-template-columns:minmax(130px,.7fr) 1.3fr;gap:.75rem;margin:0}.catalog-facts dt{font-weight:800;color:#294854}.catalog-facts dd{margin:0;color:#4c6570;word-break:break-word}.catalog-hold{margin-top:1rem;padding:1rem;border-left:4px solid #936c00;background:#fff5db;color:#574000}.catalog-hold ul{margin:.5rem 0 0;padding-left:1.2rem}.catalog-price{font-size:1.5rem;font-weight:900}
.catalog-topnav{background:#07161c;color:#fff}.catalog-topnav .catalog-nav-inner{width:min(1180px,calc(100% - 2rem));margin:0 auto;min-height:74px;display:flex;align-items:center;gap:1rem}.catalog-brand{color:#fff;text-decoration:none;font-weight:900;letter-spacing:.02em;margin-right:auto}.catalog-topnav nav{display:flex;gap:.85rem;align-items:center;flex-wrap:wrap}.catalog-topnav nav a{color:#dce9ed;text-decoration:none;font-weight:700;font-size:.9rem}.catalog-topnav nav a[aria-current="page"]{color:#fff;text-decoration:underline;text-underline-offset:5px}
.catalog-footer{background:#07161c;color:#cbd9de;padding:1.5rem 0}.catalog-footer .catalog-nav-inner{width:min(1180px,calc(100% - 2rem));margin:0 auto;display:flex;gap:1rem;flex-wrap:wrap}.catalog-footer a{color:#fff}
@media(max-width:820px){.catalog-grid{grid-template-columns:1fr 1fr}.catalog-detail{grid-template-columns:1fr}}@media(max-width:560px){.catalog-grid{grid-template-columns:1fr}.catalog-topnav .catalog-nav-inner{align-items:flex-start;padding:1rem 0;flex-direction:column}.catalog-brand{margin-right:0}.catalog-facts dl{grid-template-columns:1fr;gap:.25rem}.catalog-facts dd{margin-bottom:.7rem}}
`;
